---
title: "Riley_Meredith_HW02"
output: pdf_document
date: "2025-02-12"
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(plotly)
```

```{r}
filtered_data <- Nutrition_Physical_Activity_and_Obesity_Youth_Risk_Behavior_Surveillance_System_20250212_2 %>%
  filter(Class == c("Sugar Drinks","Television Viewing"),Total=="Total",!is.na(Data_Value)) %>%
  select(YearStart,LocationAbbr,Class,Data_Value)

pivot_data <- filtered_data %>%
  pivot_wider(id_cols=c(YearStart,LocationAbbr), names_from = Class, values_from = Data_Value)

association_data <- pivot_data %>%
  filter(!is.na(`Television Viewing`),!is.na(`Sugar Drinks`))

```

Percent of students in grades 9-12 watching 3 or more hours of television each school day
Percent of students in grades 9-12 who drank regular soda/pop at least one time per day

```{r}
tv_sugar <- association_data %>%
  plot_ly(x = ~`Television Viewing`, y = ~`Sugar Drinks`, color = ~YearStart, type = 'scatter', mode = 'markers') %>%
  layout(
    title = 'Television Viewing vs Sugar Drinks',
    xaxis = list(title = 'Television Viewing'),
    yaxis = list(title = 'Sugar Drinks')
  )
tv_sugar
```

